import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './ui/components/common/Navbar'
import ThemeProvider from './providers/ThemeProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang="en">

      <body className={`${inter.className} bg-white dark:bg-gray-800`} >
        <ThemeProvider>
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
